version: '3.9'

services:
  server:
    container_name: server
    build: .
    ports:
      - '8080:8080'
    links:
      - db
    depends_on:
      - db
  db:
    container_name: database
    image: 'postgres'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: 'free'
      POSTGRES_USER: 'free'
      POSTGRES_DB: 'cubos'
